// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import ENV from "./src/config/env.js";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: ENV["DATABASE_URL"],
    shadowDatabaseUrl: ENV["SHADOW_DATABASE_URL"],
  },
});
