CREATE DATABASE IF NOT EXISTS ragflow_admin;
CREATE DATABASE IF NOT EXISTS dataset_db;
CREATE DATABASE IF NOT EXISTS rag_flow;
CREATE DATABASE IF NOT EXISTS notification_service;
CREATE DATABASE IF NOT EXISTS search_service;
CREATE DATABASE IF NOT EXISTS identity_db;
CREATE DATABASE IF NOT EXISTS rag_dataset;
CREATE DATABASE IF NOT EXISTS notification_service;

CREATE DATABASE IF NOT EXISTS knowledgebase_db;
CREATE DATABASE IF NOT EXISTS document_db;
CREATE DATABASE IF NOT EXISTS llm_gateway;