import { ROUTES } from "@modules/identity/constants/routes";

export const ROUTE_POLICY = {
  [ROUTES.LOGIN]: "PUBLIC",
  [ROUTES.ROOT]: "PROTECTED",
  [ROUTES.DATASETS]: "PROTECTED",
  [ROUTES.DATASET]: "PROTECTED",
  [ROUTES.CHUNK_PARSED_CHUNKS]: "PROTECTED",
  [ROUTES.AGENTS]: "PROTECTED",
  [ROUTES.CHATS]: "PROTECTED",
  [ROUTES.SEARCHES]: "PROTECTED",
  [ROUTES.FILES]: "PROTECTED",
  [ROUTES.PROFILE]: "PROTECTED",
  [ROUTES.ADMIN]: "PROTECTED",
} as const;