export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login-next',
  LOGOUT: '/logout',
  HOME: '/home',
  DATASETS: '/datasets',
  DATASET_BASE: '/dataset',
  DATASET: '/dataset/dataset',
  DATASET_DETAIL: '/dataset/dataset/:id',
  AGENT: '/agent',
  AGENT_TEMPLATES: '/agent-templates',
  AGENTS: '/agents',
  MEMORIES: '/memories',
  MEMORY: '/memory',
  MEMORY_MESSAGE: '/memory-message',
  MEMORY_SETTING: '/memory-setting',
  AGENT_LIST: '/agent-list',
  SEARCHES: '/searches',
  SEARCH_BY_ID: '/searches/:id',
  SEARCH: '/next-search',
  SEARCH_SHARE: '/next-search/share',
  CHATS: '/next-chats',
  CHAT_DETAIL: '/next-chats/:dialogId',
  CHAT: '/next-chat',
  FILES: '/files',
  PROFILE_SETTING: '/profile-setting',
  PROFILE: '/profile',
  API: '/api',
  MCP: '/mcp',
  TEAM: '/team',
  PLAN: '/plan',
  MODEL: '/model',
  PROMPT: '/prompt',
  DATA_SOURCE: '/data-source',
  DATA_SOURCE_DETAIL_PAGE: '/data-source-detail-page',

  PROFILE_MCP: '/profile-setting/mcp',
  PROFILE_TEAM: '/profile-setting/team',
  PROFILE_PLAN: '/profile-setting/plan',
  PROFILE_MODEL: '/profile-setting/model',
  PROFILE_PROMPT: '/profile-setting/prompt',
  PROFILE_PROFILE: '/profile-setting/profile',

  DATASET_TESTING: '/testing',
  CHUNK: '/chunk',
  CHUNK_RESULT: '/chunk/chunk',
  CHUNK_PARSED_CHUNKS: '/chunk/parsed/chunks',
  PARSED: '/parsed',
  PARSED_RESULT: '/chunk/parsed',
  RESULT: '/result',
  RESULT_VIEW: '/chunk/result',

  KNOWLEDGE_GRAPH: '/knowledge-graph',
  AGENT_LOG_PAGE: '/agent-log-page',
  AGENT_SHARE: '/agent/share',

  CHAT_SHARE: '/next-chats/share',
  CHAT_WIDGET: '/next-chats/widget',

  USER_SETTING: '/user-setting',
  USER_SETTING_TEAM: '/user-setting/team',
  USER_SETTING_PROFILE: '/user-setting/profile',
  DATASET_OVERVIEW: '/dataset-overview',
  DATASET_SETTING: '/dataset-setting',
  DATAFLOW_RESULT: '/dataflow-result',

  ADMIN: '/admin',
  ADMIN_SERVICES: '/admin/services',
  ADMIN_USER_MANAGEMENT: '/admin/users',
  ADMIN_WHITELIST: '/admin/whitelist',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_MONITORING: '/admin/monitoring',
} as const;

export type Route = (typeof ROUTES)[keyof typeof ROUTES];